---

# Playbook site.
# Used to run all roles against the test infrastructure.


- hosts: all
  gather_facts: True
  vars:
    - dist_upgrade: True
  roles:
    - pkg_mirror
    - upgrade
    - ansible
    - hostname
    - test_env

- hosts: all
  gather_facts: False
  roles:
    - console
    - hwraid
    - hw_vm_tools
    - ipmi
    - iptables
    - mariadb
    - motd
    - network
    - nginx
    - ntp
    - pki
    - postfix
    - rpcbind
    - rsyslog
    - snmp
    - ssh
    - telegraf
    - users

- hosts: Debian_7
  gather_facts: False
  roles:
    - grub

- hosts: Debian_8
  gather_facts: False
  roles:
    - grub
    - nodejs

- hosts: Debian_9
  gather_facts: False
  roles:
    - grub
    - nodejs

- hosts: CentOS_6
  gather_facts: False
  roles: []

- hosts: CentOS_7
  gather_facts: False
  roles:
    - grub
    - nodejs

- hosts: Ubuntu_14
  gather_facts: False
  roles:
    - grub

- hosts: Ubuntu_16
  gather_facts: False
  roles:
    - grub
    - nodejs
